name: 'discord-musicbot'

networks:
  lavalink-net:

services:
  discordbot:
    build: .
    restart: unless-stopped
    networks:
      - lavalink-net
    depends_on:
      - lavalink
    volumes:
      - ./config.js:/usr/src/app/config.js:ro

  lavalink:
    image: fredboat/lavalink:3
    hostname: lavalink
    restart: unless-stopped
    ports:
      - 2333:2333
    networks:
      - lavalink-net
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml:ro
