name: 'Magi'

networks:
  lavalink-net:

services:
  discordbot:
    build: .
    restart: unless-stopped
    networks:
      - lavalink-net
    volumes:
      - ./config.js:/usr/src/app/config.js:ro
    depends_on:
      - lavalink

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3
    hostname: lavalink
    restart: unless-stopped
    networks:
      - lavalink-net
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml:ro
      # persist plugins between restarts
      - ./lavalink/plugins/:/opt/Lavalink/plugins/
    depends_on:
      - ytcipher

  ytcipher:
    image: ghcr.io/kikkia/yt-cipher:master
    hostname: ytcipher
    restart: unless-stopped
    networks:
      - lavalink-net
    environment:
      API_TOKEN: 'really_secret_password'
